# Test requests for restclient.el

# Health check
GET http://localhost:3000/api/ping

# Working login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "password2"
}

# Failing login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "bob@bobson.com",
  "password": "4321tset"
}

# Get account info
GET http://localhost:3000/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAvYXBpIiwic3ViIjoiY2M1YTVkMTYtYjgzYS00OTZkLTk5M2EtOTM2ZjQxOGUxZDNlIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaWF0IjoxNzI1NjMzODgzLCJleHAiOjE3MjU2Mzc0ODN9.hDjmDNvy2MNwGP6Th0Jl8THSq9bbg6APv4WndbvOBUk
Content-Type: application/json
