# Test requests for restclient.el

# Health check
GET http://localhost:3000/api/health-check

# Working login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "bob@bobson.com",
  "password": "test1234"
}

# Failing login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "bob@bobson.com",
  "password": "4321tset"
}
